import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import { Terminal } from "../components/Terminal";
import { MainVisual } from "../components/MainVisual";
import { Terminals } from "../components/Terminals";

const Home: NextPage = () => (
    <div className={styles.container}>
        <Head>
            <title>6th INIAD-FES</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/images/favicon.ico" />
        </Head>

        <main className={styles.main}>
            <MainVisual />

            <Terminals />

            <div id="terminals" className="flex flex-col gap-4">
                <Terminal isDeletable>
                    <div className="bg-orange-600 p-6 ">
                        <p>deletable terminal</p>
                    </div>
                </Terminal>
                <Terminal isMinimizable>
                    <div className="bg-orange-600 p-6 ">
                        <p>minimizable terminal</p>
                    </div>
                </Terminal>
                <Terminal>
                    <div className="bg-orange-600 p-6 ">
                        <p>normal terminal</p>
                    </div>
                </Terminal>
            </div>
        </main>

        <footer className={`${styles.footer} flex justify-center`}>
            <a
                href="https://iniadfes.com/"
                target="_blank"
                rel="noopener noreferrer"
            >
                6th INIAD-FES
                <span className={styles.logo}>
                    <Image
                        src="/images/clipping_6th-logo(オリジナルではない).png"
                        alt="6th INIAD-FES's logo"
                        width={128}
                        height={128}
                    />
                </span>
            </a>
        </footer>
    </div>
);

// eslint-disable-next-line import/no-default-export
export default Home;
