import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import { Terminal } from "../components/Terminal";
import { MainVisual } from "../components/MainVisual";

const Home: NextPage = () => (
    <div className={styles.container}>
        <Head>
            <title>6th INIAD-FES</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
            <div>
                <MainVisual />
                <div id="terminals" className="flex flex-col gap-4">
                    <Terminal isDeletable>
                        <div className="bg-orange-600 p-6 ">
                            <p>deletable terminal</p>
                        </div>
                    </Terminal>
                    <Terminal isMinimizable>
                        <div className="bg-orange-600 p-6 ">
                            <p>minimizable terminal</p>
                        </div>
                    </Terminal>
                    <Terminal>
                        <div className="bg-orange-600 p-6 ">
                            <p>normal terminal</p>
                        </div>
                    </Terminal>
                </div>
            </div>
        </main>

        <footer className={styles.footer}>
            <a
                href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
            >
                Powered by{" "}
                <span className={styles.logo}>
                    <Image
                        src="/vercel.svg"
                        alt="Vercel Logo"
                        width={72}
                        height={16}
                    />
                </span>
            </a>
        </footer>
    </div>
);

// eslint-disable-next-line import/no-default-export
export default Home;
