export const aboutFes: string;
export const aboutFesContainer: string;
export const aboutFesContent: string;
export const hexagon: string;
export const mainContent: string;
export const matsu: string;
export const ribbon: string;
export const ribbonContent: string;
export const title: string;
